### ISSUE TITLE
Executable shell script isn't runnable from repository root

### ISSUE THREAD

**Issue by simontoens** [salesforce/rules_spring#110]
The springboot rule is_executable.  During the build phase, the springboot rule generates a shell script, which bazel then calls when the user invokes "bazel run".  Sometimes, for debugging, it is useful to be able to run this shell script by itself.  This doesn't work from the repository root - instead the current directory has to be "bazel-bin".  This doesn't match the behavior of other shell scripts generated by rules that are executable - they are typically runnable from the repo root.

For example, assuming this target is the springboot rule target: projects/services/myservice:myservice

This doesn't work (from the repo root):
bazel-bin/projects/services/myservice/myservice

This does work, but it is less convenient:
cd bazel-bin && projects/services/myservice/myservice

**Comment by plaird** [comment]
This was opened not quite 4 years ago. Sorry for the delay, I just don't personally use this launch approach so never prioritized. Turns out it was an easy fix.

I fixed the original use case, I didn't fix the workaround use case where you first cd into bazel-bin.

```
# this works now
cd [workspace root]
./bazel-bin/examples/helloworld/helloworld
```
