### ISSUE TITLE
appjar_locator does not add the `tags` to the target

### ISSUE THREAD

**Issue by george-harness** [salesforce/rules_spring#137]
# SUBRULE 2C: CLASSPATH INDEX
    # see https://github.com/salesforce/rules_spring/issues/81
    _appjar_locator_rule(
        name = appjar_locator_rule,
        app_dep = java_library,
    )

**Comment by plaird** [comment]
Thanks @george-harness for the report. Do you need this resolved urgently, or is this just a nice-to-have?

**Comment by george-harness** [comment]
@plaird it is not urgent, but it is blocker. I have targets that I want to have tag "manual" for them, and because of this one target that depends on them, the whole chain of targets get build when using build all.

**Comment by plaird** [comment]
This was resolved in [release 2.1.4](https://github.com/salesforce/rules_spring/releases/tag/2.1.4). Thanks for reporting!

**Comment by george-harness** [comment]
Thank you @plaird. By the way there is copy/paste spelling in the release adoption script

http_archive(
    name = "rules_spring",
    sha256 = "9385652bb92d365675d1ca7c963672a8091dc5940a9e307104d3c92e7a789c8e",
    urls = [
         "https://github.com/salesforce/rules_spring/releases/download/2.1.    -->  3 instead of 4 /rules-spring-2.1.4.zip",
    ],
)

**Comment by plaird** [comment]
Ack. Thanks for spotting! Fixed.
