### ISSUE TITLE
ibazel run doesn't work, beginning with v2.1.0

### ISSUE THREAD

**Issue by drmercer-lucid** [salesforce/rules_spring#143]
Hi team,

We have a Spring server built using bazel, and we use [`ibazel`](https://github.com/bazelbuild/bazel-watcher) for local development. `ibazel run //atlassian-embed` should run the Spring server and automatically restart when any of the source files change. This was working great on rules_spring 2.0.0, but after upgrading to 2.1.0 or higher, `ibazel run` fails with these errors:

```
[bazel-bin]/atlassian-embed/atlassian-embed_deploy: 8: Bad substitution
[bazel-bin]/atlassian-embed/atlassian-embed_deploy: 11: source: not found
```

(Where `[bazel-bin]` is the full path of the `bazel-bin` dir.) Looking at [the release notes for 2.1.0](https://github.com/salesforce/rules_spring/releases/tag/2.1.0), I see some changes were made around the run script; I'll look into those and see if I can find a fix, but figured it'd be worth opening this anyway in case anyone else runs into this issue.

**Comment by plaird** [comment]
As a workaround, it may be helpful to use the custom launcher script option:
https://github.com/salesforce/rules_spring/blob/master/springboot/bazelrun.md#custom-launcher-script

until we resolve this (which appears to be a variant of #110 as you mentioned).

**Comment by drmercer-lucid** [comment]
> As a workaround, it may be helpful to use the custom launcher script option:

Unfortunately, this failure seems to happen in the script that launches the (possibly custom) launcher script. Here's the source of the `deploy` script that's failing:

```
#!/bin/bash

set -e

# bring in the resolved variables needed for running the script
# SCRIPT_DIR is the directory in which bazel run executes
SCRIPT_DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" &> /dev/null && pwd )"

# the env variables file is found in SCRIPT_DIR
source $SCRIPT_DIR/bazelrun_env.sh

# the inner bazelrun script is found in the runfiles subdir
# this is either default_bazelrun_script.sh or a custom one provided by the user
source external/rules_spring/springboot/default_bazelrun_script.sh
```

**Comment by drmercer-lucid** [comment]
I believe I found the problem. There's a newline before the shebang in the generated wrapper script:

https://github.com/salesforce/rules_spring/blob/71cf0f5636aec63ba172263d9b4c12572c4cbb27/springboot/springboot.bzl#L248-L249

This change fixes it:

```diff
-_bazelrun_script_template = """
-#!/bin/bash
+_bazelrun_script_template = """#!/bin/bash
```

I'll try to open a PR soon, but won't be upset if someone beats me to it
