### ISSUE TITLE
Make bazelrun_jvm_flags a list like for java_binary

### ISSUE THREAD

**Issue by joca-bt** [salesforce/rules_spring#167]
Make bazelrun_jvm_flags a list like for java_binary. This makes it more compatible with the java_binary rule and easier to migrate.

**Comment by plaird** [comment]
Yes good suggestion, having it as a list is more Bazel-like.

**Comment by plaird** [comment]
- bazelrun_jvm_flag_list is the new attribute that is of type list.
- old bazelrun_jvm_flags attribute will be maintained, but deprecated
