### ISSUE TITLE
Add support for Spring Boot 3.2.0 NestedFileSystemProvider

### ISSUE THREAD

**Issue by hjellek** [salesforce/rules_spring#176]
Spring Boot 3.2.0 Introduces [nested jars support](https://github.com/spring-projects/spring-boot/wiki/Spring-Boot-3.2.0-Release-Notes/0e643bbde530fc680c1dad11eeb58ab966582ee8#nested-jar-support), with a new NestedFileSystemProvider. 
This is not automatically loaded into the resulting jar with the current implementation.

It seems like [META-INF/services/java.nio.file.spi.FileSystemProvider](https://github.com/spring-projects/spring-boot/blob/5b6e3fab2cb7355d1053c71d0b4411687f463aaa/spring-boot-project/spring-boot-tools/spring-boot-loader/src/main/resources/META-INF/services/java.nio.file.spi.FileSystemProvider) is not loaded into the resulting jar when packaged.

When inspecting the jar, META-INF only contains the MANIFEST.MF file:
```
META-INF/
META-INF/MANIFEST.MF
```

while a similiar example with Maven correctly has the  `META-INF/services/java.nio.file.spi.FileSystemProvider` file correctly packaged
```
META-INF/
META-INF/MANIFEST.MF
META-INF/services/
META-INF/services/java.nio.file.spi.FileSystemProvider
```

See https://github.com/hjellek/rules_spring/blob/spring-boot-3.2.1-example/examples/helloworld/src/test/java/com/sample/SampleNesteFileSystemUnitTest.java as a simple/naive example of the error.

One workaround for now is to use the [spring-boot-loader-classic](https://github.com/spring-projects/spring-boot/tree/main/spring-boot-project/spring-boot-tools/spring-boot-loader-classic) which results in usage of the old file loader, which does not produce resources with the `jar:nested:` property.

**Comment by plaird** [comment]
OK, thanks for pointing this out.

**Comment by hjellek** [comment]
Thanks for such a fast response!
