### ISSUE TITLE
captive python instructions need to be updated

### ISSUE THREAD

**Issue by bendavini** [salesforce/rules_spring#194]
With the introduction of the module-based dependency on rules_python (https://github.com/salesforce/rules_spring/pull/190), the python toolchain from rules_python is the default, even if users want to use another (e.g., a 'captive' python).

Following the existing instructions to use a 'captive' python are insufficient; users must now either:
- specify the preferred toolchain at the command line, e.g. with  `--extra_toolchains
//tools/python_interpreter:captive_python_toolchain` or
- change `is_default = True` to `is_default = False` in MODULE.bazel for the `python.toolchain`
- ???

**Comment by plaird** [comment]
@bendavini  researched the issue and provided doc updates for this, which have been merged.

**Comment by plaird** [comment]
We are finally getting closer to migrate to bzl mod ourselves. Nice to have some of these issues already sorted out!
