### ISSUE TITLE
Create a Kotlin example for Spring Boot

### ISSUE THREAD

**Issue by plaird** [salesforce/rules_spring#84]
We are doing this internally, we should also have an example in the public repo.

To start with, let's do this in a dedicated _kotlin_example_ branch instead of master/1.1.x. We will need to remember to refresh it now and then.

**Comment by plaird** [comment]
While I created the example in the OSS repo, all the credit goes to @jeffzoch as he was the one who figured it all out first for our internal repo.

**Comment by codemeariver1** [comment]
Hey, any knowledge on when a refresh on this can come to be?

**Comment by plaird** [comment]
@codemeariver1 there is a batch of work that just came in, so I hope to tackle that soon. I will add this to the list. What version of rules_kotlin are you using?

**Comment by codemeariver1** [comment]
@plaird no worries, I understand. I'm using version 1.9.0.
